name: 'build and release electron installer'
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build/release Electron app for mac os
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: dist

      - name: Setup SSM
        if: runner.os == 'Windows'
        run: |
          cd D:\
          call powershell -command "Expand-Archive D:\a\my-first-app\my-first-app\.github\resources\smtools-windows-x64.zip"
          dir
          cd D:\smtools-windows-x64
          tree /f
          copy D:\smtools-windows-x64\smtools-windows-x64\smksp-x64.dll C:\Windows\System32\smksp.dll
          copy D:\smtools-windows-x64\smtools-windows-x64\smksp-x86.dll C:\Windows\SysWOW64\smksp.dll
          D:\smtools-windows-x64\smtools-windows-x64\smksp_registrar.exe register
          D:\smtools-windows-x64\smtools-windows-x64\smksp_registrar.exe list
          set SM_HOST=${{ secrets.SM_HOST }}
          set SM_API_KEY=${{ secrets.SM_API_KEY }}
          echo ${{ secrets.SM_CLIENT_CERT_FILE_B64 }}> D:\smtools-windows-x64\smtools-windows-x64\Certificate_pkcs12.p12.b64
          C:\Windows\System32\certutil.exe -f -decode "D:\smtools-windows-x64\smtools-windows-x64\Certificate_pkcs12.p12.b64" "D:\smtools-windows-x64\smtools-windows-x64\Certificate_pkcs12.p12"
          copy D:\smtools-windows-x64\smtools-windows-x64\Certificate_pkcs12.p12 C:\Certificate_pkcs12.p12
          set SM_CLIENT_CERT_FILE=C:\\Certificate_pkcs12.p12
          set SM_CLIENT_CERT_PASSWORD=${{ secrets.SM_CLIENT_CERT_PASSWORD }}
          D:\smtools-windows-x64\smtools-windows-x64\smctl.exe keypair ls
          C:\Windows\System32\certutil.exe -csp "DigiCert Signing Manager KSP" -key -user
          D:\smtools-windows-x64\smtools-windows-x64\smksp_cert_sync.exe
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe" sign /sha1 CB2279BB06DFB92F1F367BAC703D3F10D15781B9 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 "D:\a\my-first-app\my-first-app\dist\my-first-app Setup 1.2.21.exe"
          "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\signtool.exe" sign /sha1 CB2279BB06DFB92F1F367BAC703D3F10D15781B9 /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 "D:\a\my-first-app\my-first-app\dist\win-unpacked\my-first-app.exe"
        shell: cmd

      - name: code signing with pfx on windows-latest
        if: runner.os == 'Windows'
        uses: nakamula/code-sign-action@master
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.PASSWORD }}'
          certificatesha1: '${{ secrets.CERTHASH }}'
          certificatename: '${{ secrets.CERTNAME }}'
          folder: 'dist'
          recursive: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            dist
