name: 'build and release electron installer'
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Build/release Electron app for mac os
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: dist

      - name: Setup SSM
        if: runner.os == 'Windows'
        run: |
          copy ./.github/resources/smtools-windows-x64.zip C:\
          cd C:\
          call powershell -command "Expand-Archive smtools-windows-x64.zip"
          copy C:\smtools-windows-x64\smtools-windows-x64\smksp-x64.dll C:\Windows\System32\smksp.dll
          copy C:\smtools-windows-x64\smtools-windows-x64\smksp-x86.dll C:\Windows\SysWOW64\smksp.dll
          C:\smtools-windows-x64\smtools-windows-x64\smksp_registrar.exe register
          C:\smtools-windows-x64\smtools-windows-x64\smksp_registrar.exe list
        shell: cmd

      - name: code signing with pfx on windows-latest
        if: runner.os == 'Windows'
        uses: nakamula/code-sign-action@master
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          password: '${{ secrets.PASSWORD }}'
          certificatesha1: '${{ secrets.CERTHASH }}'
          certificatename: '${{ secrets.CERTNAME }}'
          folder: 'dist'
          recursive: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            dist
